/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class DomainmodelOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
