/**
 * generated by Xtext 2.13.0
 */
package org.etri.slice.tools.adl.jvmmodel;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtend2.lib.StringConcatenationClient;
import org.eclipse.xtext.common.types.JvmConstructor;
import org.eclipse.xtext.common.types.JvmField;
import org.eclipse.xtext.common.types.JvmFormalParameter;
import org.eclipse.xtext.common.types.JvmGenericType;
import org.eclipse.xtext.common.types.JvmMember;
import org.eclipse.xtext.common.types.JvmOperation;
import org.eclipse.xtext.common.types.JvmParameterizedTypeReference;
import org.eclipse.xtext.common.types.JvmTypeReference;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.xbase.jvmmodel.AbstractModelInferrer;
import org.eclipse.xtext.xbase.jvmmodel.IJvmDeclaredTypeAcceptor;
import org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.etri.slice.tools.adl.domainmodel.AgentDeclaration;
import org.etri.slice.tools.adl.domainmodel.Context;
import org.etri.slice.tools.adl.domainmodel.Control;
import org.etri.slice.tools.adl.domainmodel.Event;
import org.etri.slice.tools.adl.domainmodel.Feature;
import org.etri.slice.tools.adl.domainmodel.Operation;
import org.etri.slice.tools.adl.domainmodel.Property;
import org.etri.slice.tools.adl.generator.GeneratorUtils;
import org.etri.slice.tools.adl.jvmmodel.CommonInterfaces;

/**
 * <p>Infers a JVM model from the source model.</p>
 * 
 * <p>The JVM model should contain all elements that would appear in the Java code
 * which is generated from the source model. Other models link against the JVM model rather than the source model.</p>
 */
@SuppressWarnings("all")
public class DomainmodelJvmModelInferrer extends AbstractModelInferrer {
  @Inject
  @Extension
  private JvmTypesBuilder _jvmTypesBuilder;
  
  @Inject
  @Extension
  private IQualifiedNameProvider _iQualifiedNameProvider;
  
  @Inject
  @Extension
  private GeneratorUtils _generatorUtils;
  
  protected void _infer(final Context context, @Extension final IJvmDeclaredTypeAcceptor acceptor, final boolean prelinkingPhase) {
    String _name = context.getName();
    boolean _tripleEquals = (null == _name);
    if (_tripleEquals) {
      return;
    }
    final Procedure1<JvmGenericType> _function = (JvmGenericType it) -> {
      this._jvmTypesBuilder.setDocumentation(it, this._jvmTypesBuilder.getDocumentation(context));
      JvmParameterizedTypeReference _superType = context.getSuperType();
      boolean _tripleNotEquals = (_superType != null);
      if (_tripleNotEquals) {
        EList<JvmTypeReference> _superTypes = it.getSuperTypes();
        JvmTypeReference _cloneWithProxies = this._jvmTypesBuilder.cloneWithProxies(context.getSuperType());
        this._jvmTypesBuilder.<JvmTypeReference>operator_add(_superTypes, _cloneWithProxies);
      } else {
        EList<JvmTypeReference> _superTypes_1 = it.getSuperTypes();
        JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(CommonInterfaces.CONTEXT_BASE);
        this._jvmTypesBuilder.<JvmTypeReference>operator_add(_superTypes_1, _typeRef);
      }
      EList<JvmMember> _members = it.getMembers();
      final Procedure1<JvmConstructor> _function_1 = (JvmConstructor it_1) -> {
      };
      JvmConstructor _constructor = this._jvmTypesBuilder.toConstructor(context, _function_1);
      this._jvmTypesBuilder.<JvmConstructor>operator_add(_members, _constructor);
      final JvmTypeReference procedureType = this._typeReferenceBuilder.typeRef(Procedure1.class, this._typeReferenceBuilder.typeRef(it));
      EList<JvmMember> _members_1 = it.getMembers();
      final Procedure1<JvmConstructor> _function_2 = (JvmConstructor it_1) -> {
        EList<JvmFormalParameter> _parameters = it_1.getParameters();
        JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(context, "initializer", procedureType);
        this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
            _builder.append("initializer.apply(this);");
            _builder.newLine();
          }
        };
        this._jvmTypesBuilder.setBody(it_1, _client);
      };
      JvmConstructor _constructor_1 = this._jvmTypesBuilder.toConstructor(context, _function_2);
      this._jvmTypesBuilder.<JvmConstructor>operator_add(_members_1, _constructor_1);
      EList<Property> _properties = context.getProperties();
      for (final Property p : _properties) {
        String _name_1 = p.getName();
        boolean _tripleNotEquals_1 = (null != _name_1);
        if (_tripleNotEquals_1) {
          final JvmField field = this._jvmTypesBuilder.toField(p, p.getName(), p.getType());
          EList<JvmMember> _members_2 = it.getMembers();
          this._jvmTypesBuilder.<JvmField>operator_add(_members_2, field);
        }
      }
      EList<JvmMember> _members_3 = it.getMembers();
      JvmOperation _toStringMethod = this._jvmTypesBuilder.toToStringMethod(context, it);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_3, _toStringMethod);
    };
    acceptor.<JvmGenericType>accept(this._jvmTypesBuilder.toClass(context, this._generatorUtils.adaptToSlice(this._iQualifiedNameProvider.getFullyQualifiedName(context), "context")), _function);
  }
  
  protected void _infer(final org.etri.slice.tools.adl.domainmodel.Exception exc, @Extension final IJvmDeclaredTypeAcceptor acceptor, final boolean prelinkingPhase) {
    String _name = exc.getName();
    boolean _tripleEquals = (null == _name);
    if (_tripleEquals) {
      return;
    }
    final Procedure1<JvmGenericType> _function = (JvmGenericType it) -> {
      this._jvmTypesBuilder.setDocumentation(it, this._jvmTypesBuilder.getDocumentation(exc));
      JvmParameterizedTypeReference _superType = exc.getSuperType();
      boolean _tripleNotEquals = (_superType != null);
      if (_tripleNotEquals) {
        EList<JvmTypeReference> _superTypes = it.getSuperTypes();
        JvmTypeReference _cloneWithProxies = this._jvmTypesBuilder.cloneWithProxies(exc.getSuperType());
        this._jvmTypesBuilder.<JvmTypeReference>operator_add(_superTypes, _cloneWithProxies);
      } else {
        EList<JvmTypeReference> _superTypes_1 = it.getSuperTypes();
        JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(CommonInterfaces.EXCEPTION_INTERFACE);
        this._jvmTypesBuilder.<JvmTypeReference>operator_add(_superTypes_1, _typeRef);
      }
      EList<JvmMember> _members = it.getMembers();
      final Procedure1<JvmConstructor> _function_1 = (JvmConstructor it_1) -> {
      };
      JvmConstructor _constructor = this._jvmTypesBuilder.toConstructor(exc, _function_1);
      this._jvmTypesBuilder.<JvmConstructor>operator_add(_members, _constructor);
      final JvmTypeReference procedureType = this._typeReferenceBuilder.typeRef(Procedure1.class, this._typeReferenceBuilder.typeRef(it));
      EList<JvmMember> _members_1 = it.getMembers();
      final Procedure1<JvmConstructor> _function_2 = (JvmConstructor it_1) -> {
        EList<JvmFormalParameter> _parameters = it_1.getParameters();
        JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(exc, "initializer", procedureType);
        this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
            _builder.append("initializer.apply(this);");
            _builder.newLine();
          }
        };
        this._jvmTypesBuilder.setBody(it_1, _client);
      };
      JvmConstructor _constructor_1 = this._jvmTypesBuilder.toConstructor(exc, _function_2);
      this._jvmTypesBuilder.<JvmConstructor>operator_add(_members_1, _constructor_1);
    };
    acceptor.<JvmGenericType>accept(this._jvmTypesBuilder.toClass(exc, this._generatorUtils.adaptToSlice(this._iQualifiedNameProvider.getFullyQualifiedName(exc), "")), _function);
  }
  
  protected void _infer(final Event event, @Extension final IJvmDeclaredTypeAcceptor acceptor, final boolean prelinkingPhase) {
    String _name = event.getName();
    boolean _tripleEquals = (null == _name);
    if (_tripleEquals) {
      return;
    }
    final Procedure1<JvmGenericType> _function = (JvmGenericType it) -> {
      this._jvmTypesBuilder.setDocumentation(it, this._jvmTypesBuilder.getDocumentation(event));
      JvmParameterizedTypeReference _superType = event.getSuperType();
      boolean _tripleNotEquals = (_superType != null);
      if (_tripleNotEquals) {
        EList<JvmTypeReference> _superTypes = it.getSuperTypes();
        JvmTypeReference _cloneWithProxies = this._jvmTypesBuilder.cloneWithProxies(event.getSuperType());
        this._jvmTypesBuilder.<JvmTypeReference>operator_add(_superTypes, _cloneWithProxies);
      } else {
        EList<JvmTypeReference> _superTypes_1 = it.getSuperTypes();
        JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(CommonInterfaces.EVENT_BASE);
        this._jvmTypesBuilder.<JvmTypeReference>operator_add(_superTypes_1, _typeRef);
      }
      EList<JvmMember> _members = it.getMembers();
      final Procedure1<JvmConstructor> _function_1 = (JvmConstructor it_1) -> {
      };
      JvmConstructor _constructor = this._jvmTypesBuilder.toConstructor(event, _function_1);
      this._jvmTypesBuilder.<JvmConstructor>operator_add(_members, _constructor);
      final JvmTypeReference procedureType = this._typeReferenceBuilder.typeRef(Procedure1.class, this._typeReferenceBuilder.typeRef(it));
      EList<JvmMember> _members_1 = it.getMembers();
      final Procedure1<JvmConstructor> _function_2 = (JvmConstructor it_1) -> {
        EList<JvmFormalParameter> _parameters = it_1.getParameters();
        JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(event, "initializer", procedureType);
        this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
            _builder.append("initializer.apply(this);");
            _builder.newLine();
          }
        };
        this._jvmTypesBuilder.setBody(it_1, _client);
      };
      JvmConstructor _constructor_1 = this._jvmTypesBuilder.toConstructor(event, _function_2);
      this._jvmTypesBuilder.<JvmConstructor>operator_add(_members_1, _constructor_1);
      EList<Property> _properties = event.getProperties();
      for (final Property p : _properties) {
        String _name_1 = p.getName();
        boolean _tripleNotEquals_1 = (null != _name_1);
        if (_tripleNotEquals_1) {
          final JvmField field = this._jvmTypesBuilder.toField(p, p.getName(), p.getType());
          EList<JvmMember> _members_2 = it.getMembers();
          this._jvmTypesBuilder.<JvmField>operator_add(_members_2, field);
        }
      }
      EList<JvmMember> _members_3 = it.getMembers();
      JvmOperation _toStringMethod = this._jvmTypesBuilder.toToStringMethod(event, it);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_3, _toStringMethod);
    };
    acceptor.<JvmGenericType>accept(this._jvmTypesBuilder.toClass(event, this._generatorUtils.adaptToSlice(this._iQualifiedNameProvider.getFullyQualifiedName(event), "event")), _function);
  }
  
  protected void _infer(final Control control, @Extension final IJvmDeclaredTypeAcceptor acceptor, final boolean prelinkingPhase) {
    String _name = control.getName();
    boolean _tripleEquals = (null == _name);
    if (_tripleEquals) {
      return;
    }
    final Procedure1<JvmGenericType> _function = (JvmGenericType it) -> {
      this._jvmTypesBuilder.setDocumentation(it, this._jvmTypesBuilder.getDocumentation(control));
      int _size = control.getSuperTypes().size();
      boolean _greaterThan = (_size > 0);
      if (_greaterThan) {
        EList<JvmParameterizedTypeReference> _superTypes = control.getSuperTypes();
        for (final JvmParameterizedTypeReference superType : _superTypes) {
          EList<JvmTypeReference> _superTypes_1 = it.getSuperTypes();
          JvmTypeReference _cloneWithProxies = this._jvmTypesBuilder.cloneWithProxies(superType);
          this._jvmTypesBuilder.<JvmTypeReference>operator_add(_superTypes_1, _cloneWithProxies);
        }
      }
      EList<Feature> _features = control.getFeatures();
      for (final Feature f : _features) {
        boolean _matched = false;
        if (f instanceof Property) {
          _matched=true;
          String _name_1 = ((Property)f).getName();
          boolean _tripleNotEquals = (null != _name_1);
          if (_tripleNotEquals) {
            final JvmField member = this._jvmTypesBuilder.toField(f, ((Property)f).getName(), ((Property)f).getType());
            member.setStatic(true);
            EList<JvmMember> _members = it.getMembers();
            this._jvmTypesBuilder.<JvmField>operator_add(_members, member);
          }
        }
        if (!_matched) {
          if (f instanceof Operation) {
            _matched=true;
            String _name_1 = ((Operation)f).getName();
            boolean _tripleNotEquals = (null != _name_1);
            if (_tripleNotEquals) {
              EList<JvmMember> _members = it.getMembers();
              String _name_2 = ((Operation)f).getName();
              JvmTypeReference _elvis = null;
              JvmTypeReference _type = ((Operation)f).getType();
              if (_type != null) {
                _elvis = _type;
              } else {
                JvmTypeReference _inferredType = this._jvmTypesBuilder.inferredType();
                _elvis = _inferredType;
              }
              final Procedure1<JvmOperation> _function_1 = (JvmOperation it_1) -> {
                this._jvmTypesBuilder.setDocumentation(it_1, this._jvmTypesBuilder.getDocumentation(f));
                EList<JvmFormalParameter> _params = ((Operation)f).getParams();
                for (final JvmFormalParameter p : _params) {
                  EList<JvmFormalParameter> _parameters = it_1.getParameters();
                  JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(p, p.getName(), p.getParameterType());
                  this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
                }
                EList<JvmTypeReference> _exceptions = ((Operation)f).getExceptions();
                for (final JvmTypeReference e : _exceptions) {
                  EList<JvmTypeReference> _exceptions_1 = it_1.getExceptions();
                  JvmTypeReference _cloneWithProxies_1 = this._jvmTypesBuilder.cloneWithProxies(e);
                  this._jvmTypesBuilder.<JvmTypeReference>operator_add(_exceptions_1, _cloneWithProxies_1);
                }
              };
              JvmOperation _method = this._jvmTypesBuilder.toMethod(f, _name_2, _elvis, _function_1);
              this._jvmTypesBuilder.<JvmOperation>operator_add(_members, _method);
            }
          }
        }
      }
    };
    acceptor.<JvmGenericType>accept(this._jvmTypesBuilder.toInterface(control, this._generatorUtils.adaptToSlice(this._iQualifiedNameProvider.getFullyQualifiedName(control), "service").toString(), _function));
  }
  
  protected void _infer(final AgentDeclaration agent, @Extension final IJvmDeclaredTypeAcceptor acceptor, final boolean prelinkingPhase) {
  }
  
  public void infer(final EObject agent, final IJvmDeclaredTypeAcceptor acceptor, final boolean prelinkingPhase) {
    if (agent instanceof AgentDeclaration) {
      _infer((AgentDeclaration)agent, acceptor, prelinkingPhase);
      return;
    } else if (agent instanceof Context) {
      _infer((Context)agent, acceptor, prelinkingPhase);
      return;
    } else if (agent instanceof Control) {
      _infer((Control)agent, acceptor, prelinkingPhase);
      return;
    } else if (agent instanceof Event) {
      _infer((Event)agent, acceptor, prelinkingPhase);
      return;
    } else if (agent instanceof org.etri.slice.tools.adl.domainmodel.Exception) {
      _infer((org.etri.slice.tools.adl.domainmodel.Exception)agent, acceptor, prelinkingPhase);
      return;
    } else if (agent != null) {
      _infer(agent, acceptor, prelinkingPhase);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(agent, acceptor, prelinkingPhase).toString());
    }
  }
}
