package org.etri.slice.rules.fullbodydetector;

import org.etri.slice.commons.car.context.BodyPartLength;
import org.etri.slice.commons.car.event.FullBodyDetected;
import org.etri.slice.commons.car.event.ObjectDetected;
import org.etri.slice.commons.car.service.FullBodyDetector;

global FullBodyDetector fullBodyDetector;

rule "Initiate the Full-Body Detection"
	when
	   ObjectDetected($d: objInfo.distance)
	then
	   fullBodyDetector.detect($d);
end

rule "FullBody Detection Notification"
	when
		$e: BodyPartLength()
	then
		channels["car/full_body_detected"].send(new FullBodyDetected($e));
end
