/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class ADLQuickfixProvider extends XbaseQuickfixProvider {
}
