package org.etri.slice.rules.carseat;

import org.etri.slice.commons.car.event.UserSeated;
import org.etri.slice.commons.car.event.SeatPostureChanged;

global org.etri.slice.commons.car.service.SeatControl seatControl;

rule "SeatPosture Control"
	when 
		$e: UserSeated($driver: userInfo)
	then		
		seatControl.setPosture($driver);
end

rule "SeatPosture Change Notification"
	when
		$e: SeatPostureChanged()
	then
		channels["seat_posture_changed"].send($e);
end
