/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.domainmodel.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.etri.slice.tools.adl.domainmodel.DomainmodelPackage;
import org.etri.slice.tools.adl.domainmodel.RuleSet;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rule Set</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.impl.RuleSetImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.impl.RuleSetImpl#getGroup_id <em>Group id</em>}</li>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.impl.RuleSetImpl#getArtifact_id <em>Artifact id</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RuleSetImpl extends MinimalEObjectImpl.Container implements RuleSet
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getGroup_id() <em>Group id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGroup_id()
   * @generated
   * @ordered
   */
  protected static final String GROUP_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGroup_id() <em>Group id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGroup_id()
   * @generated
   * @ordered
   */
  protected String group_id = GROUP_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getArtifact_id() <em>Artifact id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArtifact_id()
   * @generated
   * @ordered
   */
  protected static final String ARTIFACT_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArtifact_id() <em>Artifact id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArtifact_id()
   * @generated
   * @ordered
   */
  protected String artifact_id = ARTIFACT_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RuleSetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainmodelPackage.Literals.RULE_SET;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.RULE_SET__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getGroup_id()
  {
    return group_id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGroup_id(String newGroup_id)
  {
    String oldGroup_id = group_id;
    group_id = newGroup_id;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.RULE_SET__GROUP_ID, oldGroup_id, group_id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getArtifact_id()
  {
    return artifact_id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setArtifact_id(String newArtifact_id)
  {
    String oldArtifact_id = artifact_id;
    artifact_id = newArtifact_id;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.RULE_SET__ARTIFACT_ID, oldArtifact_id, artifact_id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DomainmodelPackage.RULE_SET__NAME:
        return getName();
      case DomainmodelPackage.RULE_SET__GROUP_ID:
        return getGroup_id();
      case DomainmodelPackage.RULE_SET__ARTIFACT_ID:
        return getArtifact_id();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DomainmodelPackage.RULE_SET__NAME:
        setName((String)newValue);
        return;
      case DomainmodelPackage.RULE_SET__GROUP_ID:
        setGroup_id((String)newValue);
        return;
      case DomainmodelPackage.RULE_SET__ARTIFACT_ID:
        setArtifact_id((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.RULE_SET__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DomainmodelPackage.RULE_SET__GROUP_ID:
        setGroup_id(GROUP_ID_EDEFAULT);
        return;
      case DomainmodelPackage.RULE_SET__ARTIFACT_ID:
        setArtifact_id(ARTIFACT_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.RULE_SET__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DomainmodelPackage.RULE_SET__GROUP_ID:
        return GROUP_ID_EDEFAULT == null ? group_id != null : !GROUP_ID_EDEFAULT.equals(group_id);
      case DomainmodelPackage.RULE_SET__ARTIFACT_ID:
        return ARTIFACT_ID_EDEFAULT == null ? artifact_id != null : !ARTIFACT_ID_EDEFAULT.equals(artifact_id);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", group_id: ");
    result.append(group_id);
    result.append(", artifact_id: ");
    result.append(artifact_id);
    result.append(')');
    return result.toString();
  }

} //RuleSetImpl
