/*
 * generated by Xtext
 */
package org.etri.slice.tools.adl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractDomainmodelScopeProvider extends XbaseBatchScopeProvider {
}
