/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.domainmodel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Agent Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.AgentDeclaration#getAgency <em>Agency</em>}</li>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.AgentDeclaration#getRuleSet <em>Rule Set</em>}</li>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.AgentDeclaration#getBehaviorSet <em>Behavior Set</em>}</li>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.AgentDeclaration#getCommandSets <em>Command Sets</em>}</li>
 * </ul>
 *
 * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getAgentDeclaration()
 * @model
 * @generated
 */
public interface AgentDeclaration extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Agency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Agency</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agency</em>' containment reference.
   * @see #setAgency(Agency)
   * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getAgentDeclaration_Agency()
   * @model containment="true"
   * @generated
   */
  Agency getAgency();

  /**
   * Sets the value of the '{@link org.etri.slice.tools.adl.domainmodel.AgentDeclaration#getAgency <em>Agency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Agency</em>' containment reference.
   * @see #getAgency()
   * @generated
   */
  void setAgency(Agency value);

  /**
   * Returns the value of the '<em><b>Rule Set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rule Set</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule Set</em>' containment reference.
   * @see #setRuleSet(RuleSet)
   * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getAgentDeclaration_RuleSet()
   * @model containment="true"
   * @generated
   */
  RuleSet getRuleSet();

  /**
   * Sets the value of the '{@link org.etri.slice.tools.adl.domainmodel.AgentDeclaration#getRuleSet <em>Rule Set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule Set</em>' containment reference.
   * @see #getRuleSet()
   * @generated
   */
  void setRuleSet(RuleSet value);

  /**
   * Returns the value of the '<em><b>Behavior Set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Behavior Set</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behavior Set</em>' containment reference.
   * @see #setBehaviorSet(BehaviorSet)
   * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getAgentDeclaration_BehaviorSet()
   * @model containment="true"
   * @generated
   */
  BehaviorSet getBehaviorSet();

  /**
   * Sets the value of the '{@link org.etri.slice.tools.adl.domainmodel.AgentDeclaration#getBehaviorSet <em>Behavior Set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Behavior Set</em>' containment reference.
   * @see #getBehaviorSet()
   * @generated
   */
  void setBehaviorSet(BehaviorSet value);

  /**
   * Returns the value of the '<em><b>Command Sets</b></em>' containment reference list.
   * The list contents are of type {@link org.etri.slice.tools.adl.domainmodel.CommandSet}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Command Sets</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command Sets</em>' containment reference list.
   * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getAgentDeclaration_CommandSets()
   * @model containment="true"
   * @generated
   */
  EList<CommandSet> getCommandSets();

} // AgentDeclaration
