/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Agency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.Agency#getIp <em>Ip</em>}</li>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.Agency#getPort <em>Port</em>}</li>
 * </ul>
 *
 * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getAgency()
 * @model
 * @generated
 */
public interface Agency extends EObject
{
  /**
   * Returns the value of the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ip</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip</em>' attribute.
   * @see #setIp(String)
   * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getAgency_Ip()
   * @model
   * @generated
   */
  String getIp();

  /**
   * Sets the value of the '{@link org.etri.slice.tools.adl.domainmodel.Agency#getIp <em>Ip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip</em>' attribute.
   * @see #getIp()
   * @generated
   */
  void setIp(String value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getAgency_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link org.etri.slice.tools.adl.domainmodel.Agency#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

} // Agency
