/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.domainmodel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.etri.slice.tools.adl.domainmodel.BehaviorSet#getBehaviors <em>Behaviors</em>}</li>
 * </ul>
 *
 * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getBehaviorSet()
 * @model
 * @generated
 */
public interface BehaviorSet extends EObject
{
  /**
   * Returns the value of the '<em><b>Behaviors</b></em>' containment reference list.
   * The list contents are of type {@link org.etri.slice.tools.adl.domainmodel.Behavior}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Behaviors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviors</em>' containment reference list.
   * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getBehaviorSet_Behaviors()
   * @model containment="true"
   * @generated
   */
  EList<Behavior> getBehaviors();

} // BehaviorSet
