/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends EObject
{
} // DataType
