/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>No Op</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getNoOp()
 * @model
 * @generated
 */
public interface NoOp extends Action
{
} // NoOp
