/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.etri.slice.tools.adl.domainmodel.DomainmodelPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends Feature
{
} // Property
