/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl;

import org.etri.slice.tools.adl.DomainmodelStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainmodelStandaloneSetup extends DomainmodelStandaloneSetupGenerated {
  public static void doSetup() {
    new DomainmodelStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
