/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.ide;

import org.etri.slice.tools.adl.ide.AbstractDomainmodelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
