package org.etri.slice.rules.car;

import org.etri.slice.commons.car.context.BodyPartLength;
import org.etri.slice.commons.car.event.FullBodyDetected;
import org.etri.slice.commons.car.event.ObjectDetected;
import org.etri.slice.commons.car.service.FullBodyDetector;

global FullBodyDetector fullBodyDetector;

rule "Initiate full-body Detection"
	when
		$e: ObjectDetected($d: info.distance)
	then
		fullBodyDetector.detect($d);
end

rule "FullBody Detection Notificiation"
	when
		$e: BodyPartLength()
	then
		channels["full_body_detected"].send(new FullBodyDetected($e));
end

