/*
 * generated by Xtext
 */
package org.etri.slice.tools.adl.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class DomainmodelEditor extends XbaseEditor {
}
