/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.builder.BuilderParticipant;
import org.etri.slice.tools.adl.ui.AbstractDomainmodelUiModule;
import org.etri.slice.tools.adl.ui.builder.BuilderParticipantForMultiInput;
import org.etri.slice.tools.adl.utils.DomainnodeUtil;
import org.etri.slice.tools.adl.validation.domain_dependency.DomainManager;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DomainmodelUiModule extends AbstractDomainmodelUiModule {
  public Class<? extends DomainnodeUtil> bindDomainmodeUtil() {
    return DomainnodeUtil.class;
  }
  
  @Override
  public Class<? extends BuilderParticipant> bindIXtextBuilderParticipant() {
    return BuilderParticipantForMultiInput.class;
  }
  
  public Class<? extends DomainManager> bindDomainManager() {
    return DomainManager.class;
  }
  
  public DomainmodelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
