/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.serializer;

import org.etri.slice.tools.adl.serializer.AbstractDomainmodelSemanticSequencer;

@SuppressWarnings("all")
public class DomainmodelSemanticSequencer extends AbstractDomainmodelSemanticSequencer {
}
