/**
 * generated by Xtext
 */
package org.etri.slice.tools.adl.serializer;

import org.etri.slice.tools.adl.serializer.AbstractDomainmodelSyntacticSequencer;

@SuppressWarnings("all")
public class DomainmodelSyntacticSequencer extends AbstractDomainmodelSyntacticSequencer {
}
