package org.etri.slice.tools.adl.generator.compiler;

import com.google.inject.Inject;
import java.util.List;
import java.util.UUID;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.xbase.compiler.ImportManager;
import org.eclipse.xtext.xbase.lib.Extension;
import org.etri.slice.tools.adl.domainmodel.AgentDeclaration;
import org.etri.slice.tools.adl.domainmodel.Event;
import org.etri.slice.tools.adl.generator.GeneratorUtils;

@SuppressWarnings("all")
public class EventWrapperCompiler {
  @Inject
  @Extension
  private IQualifiedNameProvider _iQualifiedNameProvider;
  
  @Inject
  @Extension
  private GeneratorUtils _generatorUtils;
  
  public CharSequence compileWrapper(final Event it, final AgentDeclaration agent) {
    StringConcatenation _builder = new StringConcatenation();
    final ImportManager importManager = new ImportManager(true);
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    final CharSequence body = this.body(it, agent, importManager);
    _builder.newLineIfNotEmpty();
    {
      EObject _eContainer = it.eContainer();
      boolean _tripleNotEquals = (_eContainer != null);
      if (_tripleNotEquals) {
        _builder.append("package org.etri.slice.agents.");
        QualifiedName _fullyQualifiedName = this._iQualifiedNameProvider.getFullyQualifiedName(it.eContainer());
        _builder.append(_fullyQualifiedName);
        _builder.append(".");
        String _lowerCase = agent.getName().toLowerCase();
        _builder.append(_lowerCase);
        _builder.append(".wrapper;");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("import org.apache.felix.ipojo.annotations.Component;");
    _builder.newLine();
    _builder.append("import org.apache.felix.ipojo.annotations.Instantiate;");
    _builder.newLine();
    _builder.append("import org.apache.felix.ipojo.annotations.Invalidate;");
    _builder.newLine();
    _builder.append("import org.apache.felix.ipojo.annotations.Property;");
    _builder.newLine();
    _builder.append("import org.apache.felix.ipojo.annotations.Requires;");
    _builder.newLine();
    _builder.append("import org.apache.felix.ipojo.annotations.Validate;");
    _builder.newLine();
    _builder.append("import org.etri.slice.api.agent.Agent;");
    _builder.newLine();
    _builder.append("import org.etri.slice.api.inference.WorkingMemory;");
    _builder.newLine();
    _builder.append("import org.etri.slice.api.perception.EventStream;");
    _builder.newLine();
    _builder.append("import org.etri.slice.core.perception.MqttEventPublisher;");
    _builder.newLine();
    _builder.append("import org.etri.slice.agents.");
    QualifiedName _fullyQualifiedName_1 = this._iQualifiedNameProvider.getFullyQualifiedName(it.eContainer());
    _builder.append(_fullyQualifiedName_1);
    _builder.append(".");
    String _lowerCase_1 = agent.getName().toLowerCase();
    _builder.append(_lowerCase_1);
    _builder.append(".stream.");
    String _name = it.getName();
    _builder.append(_name);
    _builder.append("Stream;");
    _builder.newLineIfNotEmpty();
    {
      List<String> _imports = importManager.getImports();
      for(final String i : _imports) {
        _builder.append("import ");
        _builder.append(i);
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append(body);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence body(final Event it, final AgentDeclaration agent, final ImportManager importManager) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("@Component");
    _builder.newLine();
    _builder.append("@Instantiate");
    _builder.newLine();
    _builder.append("public class ");
    String _name = it.getName();
    _builder.append(_name);
    _builder.append("Channel extends MqttEventPublisher<");
    CharSequence _serialize = importManager.serialize(this._generatorUtils.toJvmGenericType(it, this._iQualifiedNameProvider.getFullyQualifiedName(it), "event"));
    _builder.append(_serialize);
    _builder.append("> {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static final long serialVersionUID = ");
    long _mostSignificantBits = UUID.randomUUID().getMostSignificantBits();
    _builder.append(_mostSignificantBits, "\t");
    _builder.append("L;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Property(name=\"topic\", value=");
    String _name_1 = it.getName();
    _builder.append(_name_1, "\t");
    _builder.append(".TOPIC)");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private String m_topic;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Property(name=\"url\", value=\"tcp://");
    String _ip = agent.getAgency().getIp();
    _builder.append(_ip, "\t");
    _builder.append(":");
    int _port = agent.getAgency().getPort();
    _builder.append(_port, "\t");
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private String m_url;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Requires");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private WorkingMemory m_wm;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Requires");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Agent m_agent;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Requires(from=");
    String _name_2 = it.getName();
    _builder.append(_name_2, "\t");
    _builder.append("Stream.SERVICE_NAME)");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private EventStream<");
    String _name_3 = it.getName();
    _builder.append(_name_3, "\t");
    _builder.append("> m_streaming;\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected  String getTopicName() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return m_topic;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected String getMqttURL() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return m_url;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected WorkingMemory getWorkingMemory() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return m_wm;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected Agent getAgent() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return m_agent;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected EventStream<");
    String _name_4 = it.getName();
    _builder.append(_name_4, "\t");
    _builder.append("> getEventStream() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return m_streaming;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Validate");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void start() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super.start();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Invalidate");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void stop() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super.stop();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
