package org.etri.slice.tools.adl.generator.compiler;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.etri.slice.tools.adl.domainmodel.AgentDeclaration;

@SuppressWarnings("all")
public class LogbackCompiler {
  public CharSequence compileLogback(final AgentDeclaration it) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("# Console appender");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<appender name=\"stdout\" class=\"ch.qos.logback.core.ConsoleAppender\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<layout class=\"ch.qos.logback.classic.PatternLayout\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("# Pattern of log message for console appender");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<Pattern>%d{HH:mm:ss.SSS} |-%-5level in %logger{32} - %msg%n");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</Pattern>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</layout>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</appender>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("# File appender");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<appender name=\"fout\" class=\"ch.qos.logback.core.FileAppender\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("# Name of a log file");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<file>log/org.etri.slice.log</file>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<append>false</append>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<encoder>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("# Pattern of log message for file appender");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<pattern>%d{HH:mm:ss.SSS} |-%-5level in %logger{32} - %msg%n");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</pattern>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</encoder>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</appender>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("# Rolling appenders");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<appender name=\"roll-by-size\"");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("class=\"ch.qos.logback.core.rolling.RollingFileAppender\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<file>log/roll-by-size/org.etri.slice.log</file>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<rollingPolicy class=\"ch.qos.logback.core.rolling.FixedWindowRollingPolicy\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<fileNamePattern>log/roll-by-size/org.etri.slice.%i.log.zip");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</fileNamePattern>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<minIndex>1</minIndex>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<maxIndex>3</maxIndex>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<totalSizeCap>1MB</totalSizeCap>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</rollingPolicy>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<triggeringPolicy");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("class=\"ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<maxFileSize>5KB</maxFileSize>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</triggeringPolicy>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<encoder>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<pattern>%-4relative [%thread] %-5level %logger{35} - %msg%n");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</pattern>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</encoder>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</appender>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<appender name=\"roll-by-time\"");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("class=\"ch.qos.logback.core.rolling.RollingFileAppender\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<file>log/roll-by-time/org.etri.slice.log</file>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<rollingPolicy class=\"ch.qos.logback.core.rolling.TimeBasedRollingPolicy\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<fileNamePattern>log/roll-by-time/org.etri.slice.%d{yyyy-MM-dd-HH-mm}.log.zip");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</fileNamePattern>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<maxHistory>20</maxHistory>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<totalSizeCap>1MB</totalSizeCap>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</rollingPolicy>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<encoder>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<pattern>%d{HH:mm:ss.SSS} |-%-5level in %logger{32} - %msg%n");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</pattern>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</encoder>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</appender>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<appender name=\"roll-by-time-and-size\"");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("class=\"ch.qos.logback.core.rolling.RollingFileAppender\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<file>log/roll-by-time-and-size/org.etri.slice.log</file>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<rollingPolicy");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("class=\"ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<fileNamePattern>log/roll-by-time-and-size/org.etri.slice.%d{yyyy-MM-dd-mm}.%i.log.zip");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</fileNamePattern>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<maxFileSize>5KB</maxFileSize>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<maxHistory>20</maxHistory>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<totalSizeCap>1MB</totalSizeCap>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</rollingPolicy>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<encoder>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<pattern>%d{HH:mm:ss.SSS} |-%-5level in %logger{32} - %msg%n");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</pattern>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</encoder>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</appender>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("# Override log level for specified package");
    _builder.newLine();
    _builder.append("<!-- \t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<logger name=\"org.etri.slice\" level=\"TRACE\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<appender-ref ref=\"roll-by-size\" />");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<appender-ref ref=\"roll-by-time\" />");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<appender-ref ref=\"roll-by-time-and-size\" />");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</logger>");
    _builder.newLine();
    _builder.append("-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<logger name=\"ch.qos.logback\" level=\"warn\" />");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<logger name=\"org.apache\" level=\"warn\" />");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<logger name=\"org.drools\" level=\"info\" />");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<logger name=\"org.etri.slice\" level=\"debug\" />");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<root level=\"info\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<appender-ref ref=\"stdout\" />");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</root>");
    _builder.newLine();
    _builder.append("</configuration>");
    _builder.newLine();
    return _builder;
  }
}
