/*
 * generated by Xtext
 */
package org.etri.slice.tools.adl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DomainmodelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/etri/slice/tools/adl/parser/antlr/internal/InternalDomainmodel.tokens");
	}
}
