/*
 * generated by Xtext
 */
package org.etri.slice.tools.adl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class DomainmodelProposalProvider extends AbstractDomainmodelProposalProvider {
}
