/*
 * generated by Xtext
 */
package org.etri.slice.tools.adl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.etri.slice.tools.adl.ui.internal.AdlActivator;

public class DomainmodelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AdlActivator.getInstance().getInjector("org.etri.slice.tools.adl.Domainmodel");
	}

}
